services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fepa-payment-service
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=development
      - PORT=3101
      - MONGO_URL=mongodb://fepa:fepa123@fepa-mongodb:27017/fepa_payment?authSource=admin
      - RABBITMQ_URL=amqp://fepa:fepa123@fepa-rabbitmq:5672
      - VNP_TMN_CODE=${VNP_TMN_CODE}
      - VNP_HASH_SECRET=${VNP_HASH_SECRET}
      - VNP_URL=${VNP_URL}
      - VNP_RETURN_URL=${VNP_RETURN_URL}

    networks:
      - fepa-network
    restart: unless-stopped

networks:
  fepa-network:
    external: true
