services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fepa-payment-service
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=production
      - PORT=3101
      - MONGO_URL=mongodb://fepa:fepa123@fepa-mongodb:27017/fepa_payment?authSource=admin
      - RABBITMQ_URL=amqp://fepa:fepa123@fepa-rabbitmq:5672
      - JWT_SECRET=${JWT_SECRET:-fepa-key}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - VNP_TMN_CODE=${VNP_TMN_CODE:-ALYMNK6P}
      - VNP_HASH_SECRET=${VNP_HASH_SECRET:-AQ0YGMP4KQ7JKOVJKY0D4LT6L50FC}
      - VNP_URL=${VNP_URL:-https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
      - VNP_RETURN_URL=${VNP_RETURN_URL:-boopappdfepa.online}

    networks:
      - fepa-network
    restart: unless-stopped

networks:
  fepa-network:
    external: true
